SPOOL C:\guest\schemasetup\VistasEmployee.txt

SET ECHO OFF;

DROP VIEW VISTA_A4;
DROP VIEW VISTA_A3;
DROP VIEW VISTA_A2;
DROP VIEW VISTA_A1;

DROP VIEW VISTA_B7;
DROP VIEW VISTA_B6;
DROP VIEW VISTA_B5;
DROP VIEW VISTA_B4;
DROP VIEW VISTA_B3;
DROP VIEW VISTA_B2;
DROP VIEW VISTA_B1;

DROP VIEW VISTA_C7;
DROP VIEW VISTA_C6;
DROP VIEW VISTA_C5;
DROP VIEW VISTA_C4;
DROP VIEW VISTA_C3;
DROP VIEW VISTA_C2;
DROP VIEW VISTA_C1;

DROP VIEW VISTA_D5;
DROP VIEW VISTA_D4;
DROP VIEW VISTA_D3;
DROP VIEW VISTA_D2;
DROP VIEW VISTA_D1;

DROP VIEW VISTA_E9;
DROP VIEW VISTA_E8;
DROP VIEW VISTA_E7;
DROP VIEW VISTA_E6;
DROP VIEW VISTA_E5;
DROP VIEW VISTA_E4;
DROP VIEW VISTA_E3;
DROP VIEW VISTA_E2;
DROP VIEW VISTA_E1;

--VISTA DEL ARBOL A

CREATE VIEW VISTA_A1 AS
SELECT * FROM EMPLOYEE, WORKS_ON;

CREATE VIEW VISTA_A2 AS
SELECT * FROM VISTA_A1, PROJECT;

CREATE VIEW VISTA_A3 AS
SELECT * FROM VISTA_A2
WHERE Pname='ProductX' 
AND PNUMBER=Pno 
AND ESSN=SSN 
AND BDATE>TO_DATE('1957-12-31', 'YYYY-MM-DD');

CREATE VIEW VISTA_A4 AS
SELECT LNAME FROM VISTA_A3;

-------------------


--VISTA DEL ARBOL B

CREATE VIEW VISTA_B1 AS
SELECT * 
FROM EMPLOYEE
WHERE BDATE>TO_DATE('1957-12-31', 'YYYY-MM-DD');

CREATE VIEW VISTA_B2 AS
SELECT * 
FROM VISTA_B1, WORKS_ON;

CREATE VIEW VISTA_B3 AS
SELECT *
FROM VISTA_B2
WHERE ESSN=SSN;

CREATE VIEW VISTA_B4 AS
SELECT *
FROM PROJECT 
WHERE Pname='ProductX';

CREATE VIEW VISTA_B5 AS
SELECT * 
FROM VISTA_B3, VISTA_B4;

CREATE VIEW VISTA_B6 AS
SELECT * 
FROM VISTA_B5
WHERE PNUMBER=PNO;

CREATE VIEW VISTA_B7 AS
SELECT LNAME Resultado_B
FROM VISTA_B6;

-------------------


--VISTA DEL ARBOL C

CREATE VIEW VISTA_C1 AS
SELECT * 
FROM PROJECT 
WHERE Pname='ProductX';

CREATE VIEW VISTA_C2 AS
SELECT * 
FROM VISTA_C1, WORKS_ON;

CREATE VIEW VISTA_C3 AS
SELECT * 
FROM VISTA_C2
WHERE PNUMBER=PNO;

CREATE VIEW VISTA_C4 AS
SELECT * 
FROM EMPLOYEE
WHERE BDATE>TO_DATE('1957-12-31', 'YYYY-MM-DD');

CREATE VIEW VISTA_C5 AS
SELECT * 
FROM VISTA_C3, VISTA_C4;

CREATE VIEW VISTA_C6 AS
SELECT * 
FROM VISTA_C5 
WHERE ESSN=SSN;

CREATE VIEW VISTA_C7 AS
SELECT LNAME Resultado_C
FROM VISTA_C6;

-----------------------

--VISTA DEL ARBOL D
CREATE VIEW VISTA_D1 AS
SELECT * from project
WHERE Pname='ProductX';

CREATE VIEW VISTA_D2 AS
SELECT *
FROM VISTA_D1, WORKS_ON
WHERE PNUMBER=PNO;

CREATE VIEW VISTA_D3 AS
SELECT * FROM EMPLOYEE
WHERE BDATE>TO_DATE('1957-12-31', 'YYYY-MM-DD');

CREATE VIEW VISTA_D4 AS
SELECT * 
FROM VISTA_D2, VISTA_D3
WHERE ESSN=SSN;

CREATE VIEW VISTA_D5 AS
SELECT LNAME Resultado_D 
FROM VISTA_D4;

--------------------------

REM VISTA DEL ARBOL E
REM VISTA_E1
CREATE VIEW VISTA_E1 AS
SELECT * from project
WHERE Pname='ProductX';
	
REM VISTA_E2
CREATE VIEW VISTA_E2 AS
SELECT PNUMBER FROM VISTA_E1;

REM VISTA_E3
CREATE VIEW VISTA_E3 AS
SELECT ESSN, PNO
FROM WORKS_ON;
	
REM VISTA_E4
CREATE VIEW VISTA_E4 AS
SELECT * FROM VISTA_E2, VISTA_E3
WHERE PNUMBER=PNO;
	
REM VISTA_E5
CREATE VIEW VISTA_E5 AS
SELECT ESSN FROM VISTA_E4;

REM VISTA_E6
CREATE VIEW VISTA_E6 AS
SELECT * from EMPLOYEE
WHERE BDATE>TO_DATE('1957-12-31', 'YYYY-MM-DD');

REM VISTA_E7
CREATE VIEW VISTA_E7 AS
SELECT SSN, LNAME
FROM VISTA_E6;
	
REM VISTA_E8
CREATE VIEW VISTA_E8 AS
SELECT * FROM VISTA_E5, VISTA_E7
WHERE ESSN=SSN;
	
REM VISTA_E9
CREATE VIEW VISTA_E9 AS
SELECT LNAME AS Resultado_E
FROM VISTA_E8;
	
SELECT LNAME CONTROL
FROM EMPLOYEE, WORKS_ON, PROJECT
WHERE Pname='ProductX' AND ESSN=SSN AND
BDATE>TO_DATE('1957-12-31', 'YYYY-MM-DD') AND
PNUMBER=PNO;

SELECT * from VISTA_B1;
PAUSE		
SELECT * from VISTA_B2;
PAUSE	
SELECT * from VISTA_B3;
PAUSE
SELECT * from VISTA_B4;
PAUSE
SELECT * from VISTA_B5;
PAUSE
SELECT * from VISTA_B6;
PAUSE
SELECT * from VISTA_B7;
PAUSE

SELECT * from VISTA_C1;
PAUSE		
SELECT * from VISTA_C2;
PAUSE	
SELECT * from VISTA_C3;
PAUSE
SELECT * from VISTA_C4;
PAUSE
SELECT * from VISTA_C5;
PAUSE
SELECT * from VISTA_C6;
PAUSE
SELECT * from VISTA_C7;
PAUSE
	
SELECT * from VISTA_D1;
PAUSE		
SELECT * from VISTA_D2;
PAUSE	
SELECT * from VISTA_D3;
PAUSE
SELECT * from VISTA_D4;
PAUSE
SELECT * from VISTA_D5;
PAUSE

SELECT * from VISTA_E1;
PAUSE		
SELECT * from VISTA_E2;
PAUSE	
SELECT * from VISTA_E3;
PAUSE
SELECT * from VISTA_E4;
PAUSE
SELECT * from VISTA_E5;
PAUSE
SELECT * from VISTA_E6;
PAUSE
SELECT * from VISTA_E7;
PAUSE
SELECT * from VISTA_E8;
PAUSE
SELECT * from VISTA_E9;
PAUSE

PROMPT CIFRAS CONTROL 
SELECT count(*) "VISTA_A1" from VISTA_A1;
SELECT count(*) "VISTA_A2" from VISTA_A2;
SELECT count(*) "VISTA_A3" from VISTA_A3;
SELECT count(*) "VISTA_A4" from VISTA_A4;

SELECT count(*) "VISTA_B1" from VISTA_B1;
SELECT count(*) "VISTA_B2" from VISTA_B2;
SELECT count(*) "VISTA_B3" from VISTA_B3;
SELECT count(*) "VISTA_B4" from VISTA_B4;
SELECT count(*) "VISTA_B5" from VISTA_B5;
SELECT count(*) "VISTA_B6" from VISTA_B6;
SELECT count(*) "VISTA_B7" from VISTA_B7;

SELECT count(*) "VISTA_C1" from VISTA_C1;
SELECT count(*) "VISTA_C2" from VISTA_C2;
SELECT count(*) "VISTA_C3" from VISTA_C3;
SELECT count(*) "VISTA_C4" from VISTA_C4;
SELECT count(*) "VISTA_C5" from VISTA_C5;
SELECT count(*) "VISTA_C6" from VISTA_C6;
SELECT count(*) "VISTA_C7" from VISTA_C7;

SELECT count(*) "VISTA_D1" from VISTA_D1;
SELECT count(*) "VISTA_D2" from VISTA_D2;
SELECT count(*) "VISTA_D3" from VISTA_D3;
SELECT count(*) "VISTA_D4" from VISTA_D4;
SELECT count(*) "VISTA_D5" from VISTA_D5;

SELECT count(*) "VISTA_E1" from VISTA_E1;
SELECT count(*) "VISTA_E2" from VISTA_E2;
SELECT count(*) "VISTA_E3" from VISTA_E3;
SELECT count(*) "VISTA_E4" from VISTA_E4;
SELECT count(*) "VISTA_E5" from VISTA_E5;
SELECT count(*) "VISTA_E6" from VISTA_E6;
SELECT count(*) "VISTA_E7" from VISTA_E7;
SELECT count(*) "VISTA_E8" from VISTA_E8;
SELECT count(*) "VISTA_E9" from VISTA_E9;

SPOOL OFF

--GRANT CREATE VIEW TO c##employee;
